### PR TITLE
Allow consumers to disable DNS resolution on a per request basis

### PR DESCRIPTION
**Pull request by phamann**
Allow consumers to disable DNS resolution on a per request basis via an option parameter.

### CODE REVIEW

**Comment by matthew-andrews** [comment]
what's the use case?

**Comment by phamann** [comment]
Article application wants to fetch a CDN cached version of content when fetching single item but still resolve DNS for all other requests therefore cannot use the env var and must be passed as option on a per request basis.

**Comment by matthew-andrews** [comment]
i think you've got your endpoints crossed…  i don't think this is going to do what you expect

**Comment by matthew-andrews** [comment]
next-elastic.ft.com => DNS magic to ES
next-es-interface.ft.com => A Fastly cached Node app

The latter is what you want to use and you can just do regular http requests to that.

**Comment by matthew-andrews** [comment]
[i'm sorry this is so complicated 😞]

**Pull request closed without merging**
